language: rust
notifications:
    irc: "irc.mozilla.org#piston-internals"
env:
    global:
        - secure: fetkajXgb3y9uAsgbEgmtnxwgTaifFhSwOzSYXKOj8kYnmIzU2OcQCtKoa/8zDTH3hNC6Yvg4QKF0vEopY22UP8YG4ky+QbFwEu3WcLyIZm1D1wOTnXqenyGod662bTP7fZMzDMIOu3vuUXR4SpmNJl5+k7d22SvChj2bc6V2Ok=
        - LD_LIBRARY_PATH: /usr/local/lib
os:
    - linux
    - osx
before_script:
    - rustc -v
    - cargo -V
before_install:
    - curl -O http://www.libsdl.org/release/SDL2-2.0.0.tar.gz
    - tar -xzvf SDL2-2.0.0.tar.gz
install:
    - (cd SDL2-2.0.0 && ./configure && make && sudo make install)
script:
    - cargo build -v
    - cargo test -v
    - cargo doc -v
after_success:
    - cp -R target/doc doc
    - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
    - rm -r doc
