[package]

name = "piston"
version = "0.0.0"
authors = [
    "bvssvni <bvssvni@gmail.com>",
    "Coeuvre <coeuvre@gmail.com>",
    "gmorenz",
    "leonkunert <info@leonkunert.de>",
    "mitchmindtree <me@michellnordine.com>",
    "Christiandh",
    "Apointos",
    "ccgn",
    "reem",
    "TyOverby <ty@pre-alpha.com>"]

[lib]

name = "piston"
path = "./src/lib.rs"

[dependencies.vecmath]

git = "https://github.com/PistonDevelopers/vecmath"

[dependencies.shader_version]

git = "https://github.com/pistondevelopers/shader_version"

[dependencies.image]

git = "https://github.com/pistondevelopers/rust-image"

