[package]

name = "piston"
version = "0.1.3"
authors = [
    "bvssvni <bvssvni@gmail.com>",
    "Coeuvre <coeuvre@gmail.com>",
    "gmorenz",
    "leonkunert <info@leonkunert.de>",
    "mitchmindtree <me@michellnordine.com>",
    "Christiandh",
    "Apointos",
    "ccgn",
    "reem",
    "TyOverby <ty@pre-alpha.com>",
    "eddyb"
]
keywords = ["piston", "game", "engine", "core"]
description = "The Piston game engine core libraries"
license = "MIT"
repository = "https://github.com/pistondevelopers/piston.git"
homepage = "https://github.com/pistondevelopers/piston"

[lib]

name = "piston"
path = "./src/lib.rs"

[dependencies.pistoncore-input]
#git = "https://github.com/pistondevelopers/input"
version = "0.0.9"

[dependencies.pistoncore-event]
#git = "https://github.com/pistondevelopers/event"
version = "0.1.0"

[dependencies.pistoncore-window]
#git = "https://github.com/pistondevelopers/window"
version = "0.1.2"
