[package]

name = "piston"
version = "0.0.0"
authors = [
    "bvssvni <bvssvni@gmail.com>",
    "Coeuvre <coeuvre@gmail.com>",
    "gmorenz",
    "leonkunert <info@leonkunert.de>",
    "mitchmindtree <me@michellnordine.com>",
    "Christiandh",
    "Apointos",
    "ccgn",
    "reem",
    "TyOverby <ty@pre-alpha.com>",
    "eddyb"
]

[lib]

name = "piston"
path = "./src/lib.rs"

[dependencies.vecmath]

git = "https://github.com/pistondevelopers/vecmath"

[dependencies.input]

git = "https://github.com/pistondevelopers/input"

[dependencies.event]

git = "https://github.com/pistondevelopers/event"

[dependencies.shader_version]

git = "https://github.com/pistondevelopers/shader_version"

[dependencies.cam]

git = "https://github.com/pistondevelopers/cam"

[dependencies.image]

git = "https://github.com/pistondevelopers/image"

[dependencies.fps_counter]

git = "https://github.com/pistondevelopers/fps_counter"

[dependencies.drag_controller]

git = "https://github.com/pistondevelopers/drag_controller"

[dependencies.select_color]

git = "https://github.com/pistondevelopers/select_color"

[dependencies.read_color]

git = "https://github.com/pistondevelopers/read_color"

[dependencies.texture-packer]

git = "https://github.com/PistonDevelopers/texture-packer"

[dependencies.graphics]

git = "https://github.com/pistondevelopers/graphics"

[dependencies.opengl_graphics]

git = "https://github.com/pistondevelopers/opengl_graphics"

[dependencies.gfx_graphics]

git = "https://github.com/pistondevelopers/gfx_graphics"

[dependencies.sprite]

git = "https://github.com/pistondevelopers/sprite"

[dependencies.sdl2_window]

git = "https://github.com/pistondevelopers/sdl2_window"

[dependencies.wavefront-obj]

git = "https://github.com/pistondevelopers/wavefront-obj"

[dependencies.noise]

git = "https://github.com/bjz/noise-rs"

[dependencies.genmesh]

git = "https://github.com/csherratt/genmesh.git"

[dependencies.gfx]

git = "https://github.com/gfx-rs/gfx-rs"

[dependencies.wire]

git = "https://github.com/TyOverby/wire"

[dependencies.img_hash]

git = "https://github.com/cybergeek94/img_hash"

