[package]

name = "piston"
version = "0.0.0"
authors = [
    "bvssvni <bvssvni@gmail.com>",
    "Coeuvre <coeuvre@gmail.com>",
    "gmorenz",
    "leonkunert <info@leonkunert.de>",
    "mitchmindtree <me@michellnordine.com>",
    "Christiandh",
    "Apointos",
    "ccgn",
    "reem",
    "TyOverby <ty@pre-alpha.com>",
    "eddyb"
]

[lib]

name = "piston"
path = "./src/lib.rs"

[dependencies.vecmath]

git = "https://github.com/pistondevelopers/vecmath"

[dependencies.pistoncore-input]

git = "https://github.com/pistondevelopers/input"

[dependencies.pistoncore-event]

git = "https://github.com/pistondevelopers/event"

[dependencies.shader_version]

git = "https://github.com/pistondevelopers/shader_version"

[dependencies.piston3d-cam]

git = "https://github.com/pistondevelopers/cam"

[dependencies.image]

git = "https://github.com/pistondevelopers/image"

[dependencies.fps_counter]

git = "https://github.com/pistondevelopers/fps_counter"

[dependencies.piston2d-drag_controller]

git = "https://github.com/pistondevelopers/drag_controller"

[dependencies.select_color]

git = "https://github.com/pistondevelopers/select_color"

[dependencies.read_color]

git = "https://github.com/pistondevelopers/read_color"

[dependencies.piston2d-graphics]

git = "https://github.com/pistondevelopers/graphics"

[dependencies.piston2d-opengl_graphics]

git = "https://github.com/pistondevelopers/opengl_graphics"

[dependencies.piston2d-gfx_graphics]

optional = true
git = "https://github.com/pistondevelopers/gfx_graphics"

[dependencies.piston-ai_behavior]

git = "https://github.com/pistondevelopers/ai_behavior"

[dependencies.pistoncore-sdl2_window]

git = "https://github.com/pistondevelopers/sdl2_window"

[dependencies.sdl2]

git = "https://github.com/pistondevelopers/rust-sdl2"
#version = "*"

[dependencies.gfx]

optional = true
git = "https://github.com/gfx-rs/gfx-rs"

[features]
default = []
include_gfx = ["gfx", "piston2d-gfx_graphics"]

